# Generated by Django 2.1.4 on 2018-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordbin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptoken',
            name='permissions',
            field=models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('RW', 'Read and Write')], default='W', max_length=2),
        ),
    ]
