# Generated by Django 2.1.4 on 2018-12-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordbin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
