# Generated by Django 2.1.3 on 2018-11-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordbin', '0002_record_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='token',
        ),
    ]
